/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.view;

import app.model.NhanVien;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import myclass.ClockThread;

/**
 *
 * @author Admin
 */
public class MainApplicationView1 extends javax.swing.JFrame {

    /**
     * Creates new form MainApplication
     */
// 
//    private BanHangMainPane banHangMainPanel;  // Hậu Lỗi 
    private BanHangMainPanelfix banHangMainPanel; // Hậu

//    private HoaDonMainPanel hoaDonMainPanel; // Bình
    
    private HoaDonMainPanel1 hoaDonMainPanel; // Bình

    private KhachHangMainPanel khachHangMainPanel; // Hà

    private KhuyenMaiMainPanel khuyenMaiMainPanel; // Thảo

    private NhanVienMainPanel nhanVienMainPanel; // Hà

    private SanPhamMainPanel sanPhamMainPanel; // Công

    private ThongKeMainPanel thongKeMainPanel; // Thảo

    private DoiMatKhauMainPanel doiMatKhauMainPanel;

    private static NhanVien nhanVienDangNhap;

    public MainApplicationView1(NhanVien nhanVien) {
        initComponents();
        nhanVienDangNhap = nhanVien;
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

//        banHangMainPanel = new BanHangMainPane();
        hoaDonMainPanel = new HoaDonMainPanel1();

        khachHangMainPanel = new KhachHangMainPanel();

        khuyenMaiMainPanel = new KhuyenMaiMainPanel();

        nhanVienMainPanel = new NhanVienMainPanel();

        sanPhamMainPanel = new SanPhamMainPanel();

        thongKeMainPanel = new ThongKeMainPanel();

        banHangMainPanel = new BanHangMainPanelfix();

        doiMatKhauMainPanel = new DoiMatKhauMainPanel();

        labelShowName.setText("Tên :" + nhanVien.getHoTen());
        labelShowOffice.setText("Chức vụ : " + nhanVien.getVaiTro());

        if (nhanVien.getVaiTro().equalsIgnoreCase("Nhân viên")) {
            panelControl.remove(nhanVienPanel);
            panelControl.remove(thongKePanel);
   
            revalidate();
            repaint();
            showPanel(banHangMainPanel);
        } else if (nhanVien.getVaiTro().equalsIgnoreCase("Quản Lý")) {
            showPanel(thongKeMainPanel);
        }
    }

    private static ImageIcon loadImageIcon(String path) {
        URL imgURL = MainApplicationView1.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changePasswordDialog = new javax.swing.JDialog();
        changePassContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelControl = new swing.PanelGradiente();
        banHangPanel = new javax.swing.JPanel();
        banHangLabel = new javax.swing.JLabel();
        sanPhamPanel = new javax.swing.JPanel();
        sanPhamLabel1 = new javax.swing.JLabel();
        nhanVienPanel = new javax.swing.JPanel();
        nhanVienLabel1 = new javax.swing.JLabel();
        hoaDonPanel = new javax.swing.JPanel();
        hoaDonLabel1 = new javax.swing.JLabel();
        khuyenMaiPanel = new javax.swing.JPanel();
        khuyenMaiLabel1 = new javax.swing.JLabel();
        khachHangPanel = new javax.swing.JPanel();
        khachHangLabel1 = new javax.swing.JLabel();
        thongKePanel = new javax.swing.JPanel();
        thongKeLabel1 = new javax.swing.JLabel();
        labelShowOffice = new javax.swing.JLabel();
        labelShowName = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        exitStatusLb1 = new javax.swing.JPanel();
        exitLb1 = new javax.swing.JLabel();
        doiMatKhauPanel = new javax.swing.JPanel();
        doiMatKhau1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNgay = new javax.swing.JLabel();
        lblGio = new javax.swing.JLabel();

        changePassContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Đổi Mật Khẩu");

        jLabel2.setText("Mật Khẩu Cũ");

        jLabel3.setText("Mật Khẩu Mới");

        jLabel4.setText("Xác Nhận Mật Khẩu Mới");

        javax.swing.GroupLayout changePassContainerLayout = new javax.swing.GroupLayout(changePassContainer);
        changePassContainer.setLayout(changePassContainerLayout);
        changePassContainerLayout.setHorizontalGroup(
            changePassContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePassContainerLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(changePassContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(changePassContainerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(159, 159, 159))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        changePassContainerLayout.setVerticalGroup(
            changePassContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout changePasswordDialogLayout = new javax.swing.GroupLayout(changePasswordDialog.getContentPane());
        changePasswordDialog.getContentPane().setLayout(changePasswordDialogLayout);
        changePasswordDialogLayout.setHorizontalGroup(
            changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changePassContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        changePasswordDialogLayout.setVerticalGroup(
            changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changePassContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Hans Shop");
        setPreferredSize(new java.awt.Dimension(1500, 790));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setAutoscrolls(true);
        mainPanel.setPreferredSize(new java.awt.Dimension(1300, 790));
        mainPanel.setLayout(new java.awt.CardLayout());

        panelControl.setColorPrimario(new java.awt.Color(204, 204, 0));
        panelControl.setColorSecundario(new java.awt.Color(0, 102, 0));
        panelControl.setOpaque(true);
        panelControl.setPreferredSize(new java.awt.Dimension(175, 800));

        banHangPanel.setBackground(new java.awt.Color(51, 102, 0));
        banHangPanel.setPreferredSize(new java.awt.Dimension(163, 36));

        banHangLabel.setBackground(new java.awt.Color(204, 0, 204));
        banHangLabel.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        banHangLabel.setForeground(new java.awt.Color(255, 255, 255));
        banHangLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/selling.png"))); // NOI18N
        banHangLabel.setText("BÁN HÀNG");
        banHangLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        banHangLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banHangLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                banHangLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout banHangPanelLayout = new javax.swing.GroupLayout(banHangPanel);
        banHangPanel.setLayout(banHangPanelLayout);
        banHangPanelLayout.setHorizontalGroup(
            banHangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, banHangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banHangLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        banHangPanelLayout.setVerticalGroup(
            banHangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banHangLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        sanPhamPanel.setBackground(new java.awt.Color(51, 102, 0));
        sanPhamPanel.setPreferredSize(new java.awt.Dimension(163, 36));

        sanPhamLabel1.setBackground(new java.awt.Color(153, 255, 153));
        sanPhamLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        sanPhamLabel1.setForeground(new java.awt.Color(255, 255, 255));
        sanPhamLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/sneakers.png"))); // NOI18N
        sanPhamLabel1.setText("SẢN PHẨM");
        sanPhamLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sanPhamLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sanPhamLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sanPhamPanelLayout = new javax.swing.GroupLayout(sanPhamPanel);
        sanPhamPanel.setLayout(sanPhamPanelLayout);
        sanPhamPanelLayout.setHorizontalGroup(
            sanPhamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sanPhamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sanPhamLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sanPhamPanelLayout.setVerticalGroup(
            sanPhamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sanPhamLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nhanVienPanel.setBackground(new java.awt.Color(51, 102, 0));
        nhanVienPanel.setPreferredSize(new java.awt.Dimension(163, 36));

        nhanVienLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        nhanVienLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nhanVienLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/User Male.png"))); // NOI18N
        nhanVienLabel1.setText("NHÂN VIÊN");
        nhanVienLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanVienLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nhanVienPanelLayout = new javax.swing.GroupLayout(nhanVienPanel);
        nhanVienPanel.setLayout(nhanVienPanelLayout);
        nhanVienPanelLayout.setHorizontalGroup(
            nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhanVienPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhanVienLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        nhanVienPanelLayout.setVerticalGroup(
            nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nhanVienLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        hoaDonPanel.setBackground(new java.awt.Color(51, 102, 0));
        hoaDonPanel.setPreferredSize(new java.awt.Dimension(163, 36));

        hoaDonLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        hoaDonLabel1.setForeground(new java.awt.Color(255, 255, 255));
        hoaDonLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/Document.png"))); // NOI18N
        hoaDonLabel1.setText("HÓA ĐƠN");
        hoaDonLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoaDonLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hoaDonPanelLayout = new javax.swing.GroupLayout(hoaDonPanel);
        hoaDonPanel.setLayout(hoaDonPanelLayout);
        hoaDonPanelLayout.setHorizontalGroup(
            hoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoaDonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hoaDonLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        hoaDonPanelLayout.setVerticalGroup(
            hoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hoaDonLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        khuyenMaiPanel.setBackground(new java.awt.Color(51, 102, 0));
        khuyenMaiPanel.setPreferredSize(new java.awt.Dimension(163, 36));

        khuyenMaiLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        khuyenMaiLabel1.setForeground(new java.awt.Color(255, 255, 255));
        khuyenMaiLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/voucher.png"))); // NOI18N
        khuyenMaiLabel1.setText("KHUYẾN MÃI");
        khuyenMaiLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khuyenMaiLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout khuyenMaiPanelLayout = new javax.swing.GroupLayout(khuyenMaiPanel);
        khuyenMaiPanel.setLayout(khuyenMaiPanelLayout);
        khuyenMaiPanelLayout.setHorizontalGroup(
            khuyenMaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, khuyenMaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(khuyenMaiLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        khuyenMaiPanelLayout.setVerticalGroup(
            khuyenMaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khuyenMaiLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        khachHangPanel.setBackground(new java.awt.Color(51, 102, 0));
        khachHangPanel.setPreferredSize(new java.awt.Dimension(163, 36));

        khachHangLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        khachHangLabel1.setForeground(new java.awt.Color(255, 255, 255));
        khachHangLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/User Male.png"))); // NOI18N
        khachHangLabel1.setText("KHÁCH HÀNG");
        khachHangLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHangLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout khachHangPanelLayout = new javax.swing.GroupLayout(khachHangPanel);
        khachHangPanel.setLayout(khachHangPanelLayout);
        khachHangPanelLayout.setHorizontalGroup(
            khachHangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(khachHangLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        khachHangPanelLayout.setVerticalGroup(
            khachHangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khachHangLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        thongKePanel.setBackground(new java.awt.Color(51, 102, 0));
        thongKePanel.setPreferredSize(new java.awt.Dimension(163, 36));

        thongKeLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        thongKeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        thongKeLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/description.png"))); // NOI18N
        thongKeLabel1.setText("THỐNG KÊ");
        thongKeLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKeLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout thongKePanelLayout = new javax.swing.GroupLayout(thongKePanel);
        thongKePanel.setLayout(thongKePanelLayout);
        thongKePanelLayout.setHorizontalGroup(
            thongKePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongKePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thongKeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        thongKePanelLayout.setVerticalGroup(
            thongKePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thongKeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        labelShowOffice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelShowOffice.setForeground(new java.awt.Color(255, 255, 255));
        labelShowOffice.setText("Chức Vụ:");

        labelShowName.setBackground(new java.awt.Color(204, 255, 204));
        labelShowName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelShowName.setForeground(new java.awt.Color(255, 255, 255));
        labelShowName.setText("Tên:");

        exitPanel.setBackground(new java.awt.Color(0, 102, 51));
        exitPanel.setPreferredSize(new java.awt.Dimension(163, 36));

        exitStatusLb1.setBackground(new java.awt.Color(255, 255, 255));
        exitStatusLb1.setOpaque(false);
        exitStatusLb1.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout exitStatusLb1Layout = new javax.swing.GroupLayout(exitStatusLb1);
        exitStatusLb1.setLayout(exitStatusLb1Layout);
        exitStatusLb1Layout.setHorizontalGroup(
            exitStatusLb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        exitStatusLb1Layout.setVerticalGroup(
            exitStatusLb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        exitLb1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        exitLb1.setForeground(new java.awt.Color(255, 255, 255));
        exitLb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/logout.png"))); // NOI18N
        exitLb1.setText("THOÁT");
        exitLb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLb1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitStatusLb1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitLb1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitStatusLb1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(exitLb1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        doiMatKhauPanel.setBackground(new java.awt.Color(51, 102, 0));
        doiMatKhauPanel.setPreferredSize(new java.awt.Dimension(163, 36));

        doiMatKhau1.setBackground(new java.awt.Color(102, 153, 0));
        doiMatKhau1.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        doiMatKhau1.setForeground(new java.awt.Color(255, 255, 255));
        doiMatKhau1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icon/Key.png"))); // NOI18N
        doiMatKhau1.setText("ĐỔI MẬT KHẨU");
        doiMatKhau1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doiMatKhau1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout doiMatKhauPanelLayout = new javax.swing.GroupLayout(doiMatKhauPanel);
        doiMatKhauPanel.setLayout(doiMatKhauPanelLayout);
        doiMatKhauPanelLayout.setHorizontalGroup(
            doiMatKhauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doiMatKhauPanelLayout.createSequentialGroup()
                .addComponent(doiMatKhau1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        doiMatKhauPanelLayout.setVerticalGroup(
            doiMatKhauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doiMatKhau1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.setOpaque(false);

        lblNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(255, 255, 255));
        lblNgay.setText("Ngày :");

        lblGio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGio.setForeground(new java.awt.Color(255, 255, 255));
        lblGio.setText("giờ :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        panelControl.setLayer(banHangPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(sanPhamPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(nhanVienPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(hoaDonPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(khuyenMaiPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(khachHangPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(thongKePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(labelShowOffice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(labelShowName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(exitPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(doiMatKhauPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelControl.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(banHangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(sanPhamPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(nhanVienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(hoaDonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(khuyenMaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(khachHangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(thongKePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(labelShowName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelShowOffice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doiMatKhauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelShowName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelShowOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(banHangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sanPhamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhanVienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hoaDonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(khuyenMaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(khachHangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thongKePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doiMatKhauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        changePasswordDialog.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed

    }//GEN-LAST:event_btnConfirmActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ClockThread clockThread = new ClockThread(lblNgay, lblGio);
        Thread t1 = new Thread(clockThread);
        t1.start();
    }//GEN-LAST:event_formWindowOpened

    private void banHangLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banHangLabelMouseClicked
        // TODO add your handling code here:
        onClicked(banHangPanel);
        unClicked(sanPhamPanel);
        unClicked(khachHangPanel);
        unClicked(khuyenMaiPanel);
        unClicked(hoaDonPanel);
        unClicked(thongKePanel);
        unClicked(nhanVienPanel);
        unClicked(doiMatKhauPanel);
        showPanel(banHangMainPanel);
    }//GEN-LAST:event_banHangLabelMouseClicked

    private void sanPhamLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanPhamLabel1MouseClicked
        // TODO add your handling code here:
        unClicked(banHangPanel);
        onClicked(sanPhamPanel);
        unClicked(khachHangPanel);
        unClicked(khuyenMaiPanel);
        unClicked(hoaDonPanel);
        unClicked(thongKePanel);
        unClicked(nhanVienPanel);
        unClicked(doiMatKhauPanel);
        showPanel(sanPhamMainPanel);
    }//GEN-LAST:event_sanPhamLabel1MouseClicked

    private void nhanVienLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienLabel1MouseClicked
        // TODO add your handling code here:
        if (!nhanVienDangNhap.getVaiTro().equalsIgnoreCase("Quản Lý")) {
            JOptionPane.showMessageDialog(this, "Chỉ Quản Lý mới có quyền truy cập");
            return;
        }

        onClicked(nhanVienPanel);
        unClicked(sanPhamPanel);
        unClicked(banHangPanel);
        unClicked(khachHangPanel);
        unClicked(khuyenMaiPanel);
        unClicked(hoaDonPanel);
        unClicked(thongKePanel);
        unClicked(doiMatKhauPanel);
        showPanel(nhanVienMainPanel);
    }//GEN-LAST:event_nhanVienLabel1MouseClicked

    private void hoaDonLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoaDonLabel1MouseClicked
        // TODO add your handling code here:
        onClicked(hoaDonPanel);
        unClicked(nhanVienPanel);
        unClicked(sanPhamPanel);
        unClicked(banHangPanel);
        unClicked(khachHangPanel);
        unClicked(khuyenMaiPanel);
        unClicked(thongKePanel);
        unClicked(doiMatKhauPanel);
        showPanel(hoaDonMainPanel);
    }//GEN-LAST:event_hoaDonLabel1MouseClicked

    private void khuyenMaiLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khuyenMaiLabel1MouseClicked
        // TODO add your handling code here:
        onClicked(khuyenMaiPanel);
        unClicked(khachHangPanel);
        unClicked(hoaDonPanel);
        unClicked(nhanVienPanel);
        unClicked(sanPhamPanel);
        unClicked(banHangPanel);
        unClicked(thongKePanel);
        unClicked(doiMatKhauPanel);
        showPanel(khuyenMaiMainPanel);
    }//GEN-LAST:event_khuyenMaiLabel1MouseClicked

    private void khachHangLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHangLabel1MouseClicked
        // TODO add your handling code here:
        onClicked(khachHangPanel);
        unClicked(hoaDonPanel);
        unClicked(nhanVienPanel);
        unClicked(sanPhamPanel);
        unClicked(banHangPanel);
        unClicked(khuyenMaiPanel);
        unClicked(thongKePanel);
        unClicked(doiMatKhauPanel);
        showPanel(khachHangMainPanel);
    }//GEN-LAST:event_khachHangLabel1MouseClicked

    private void thongKeLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeLabel1MouseClicked
        // TODO add your handling code here:
        onClicked(thongKePanel);
        unClicked(khuyenMaiPanel);
        unClicked(khachHangPanel);
        unClicked(hoaDonPanel);
        unClicked(nhanVienPanel);
        unClicked(sanPhamPanel);
        unClicked(banHangPanel);
        unClicked(doiMatKhauPanel);
        showPanel(thongKeMainPanel);
    }//GEN-LAST:event_thongKeLabel1MouseClicked

    private void exitLb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLb1MouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_exitLb1MouseClicked

    private void doiMatKhau1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doiMatKhau1MouseClicked
        // TODO add your handling code here:
        onClicked(doiMatKhauPanel);
        unClicked(thongKePanel);
        unClicked(khuyenMaiPanel);
        unClicked(khachHangPanel);
        unClicked(hoaDonPanel);
        unClicked(nhanVienPanel);
        unClicked(sanPhamPanel);
        unClicked(banHangPanel);
        showPanel(doiMatKhauMainPanel);
    }//GEN-LAST:event_doiMatKhau1MouseClicked

    private void banHangLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banHangLabelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_banHangLabelMousePressed

    private void onClicked(JPanel panelBackGroud) {
        panelBackGroud.setBackground(new Color(200, 22, 51));
    }

    private void unClicked(JPanel panelBackGroud) {
        panelBackGroud.setBackground(new Color(51, 102, 0));
    }

    private void showPanel(JPanel panel) {
        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    public final static NhanVien getNhanVienDangNhap() {
        return nhanVienDangNhap;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//
//                new MainApplicationView().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banHangLabel;
    private javax.swing.JPanel banHangPanel;
    private javax.swing.JPanel changePassContainer;
    private javax.swing.JDialog changePasswordDialog;
    private javax.swing.JLabel doiMatKhau1;
    private javax.swing.JPanel doiMatKhauPanel;
    private javax.swing.JLabel exitLb1;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel exitStatusLb1;
    private javax.swing.JLabel hoaDonLabel1;
    private javax.swing.JPanel hoaDonPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel khachHangLabel1;
    private javax.swing.JPanel khachHangPanel;
    private javax.swing.JLabel khuyenMaiLabel1;
    private javax.swing.JPanel khuyenMaiPanel;
    private javax.swing.JLabel labelShowName;
    private javax.swing.JLabel labelShowOffice;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nhanVienLabel1;
    private javax.swing.JPanel nhanVienPanel;
    private swing.PanelGradiente panelControl;
    private javax.swing.JLabel sanPhamLabel1;
    private javax.swing.JPanel sanPhamPanel;
    private javax.swing.JLabel thongKeLabel1;
    private javax.swing.JPanel thongKePanel;
    // End of variables declaration//GEN-END:variables

}
